# Generated by Django 3.2 on 2024-10-31 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concierto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(default='2024-10-31')),
                ('Hora', models.TimeField(default='00:00')),
                ('Lugar', models.CharField(max_length=100)),
                ('Categoria', models.CharField(default='General', max_length=15)),
                ('Capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RUT', models.CharField(max_length=12, unique=True)),
                ('Nombre', models.CharField(max_length=20)),
                ('Apellido', models.CharField(max_length=20)),
                ('Telefono', models.CharField(max_length=20)),
                ('Edad', models.IntegerField()),
                ('Correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoria', models.CharField(default='Estándar', max_length=50)),
                ('Descripcion', models.CharField(max_length=50)),
                ('NumeroAsiento', models.IntegerField(default=1)),
                ('Precio', models.IntegerField()),
                ('Sector', models.CharField(max_length=50)),
                ('concierto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EntradaApp.concierto')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EntradaApp.persona')),
            ],
        ),
    ]
